[workspace]
authors = ["K. S. Ernest (iFire) Lee <32321+fire@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "launcher"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
zig = "==0.16.0"
